# Generated by Django 3.2.23 on 2023-11-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ticker_symbol', models.TextField(unique=True)),
                ('cik', models.IntegerField(unique=True)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('cash_flow', 'Cash Flow')])),
                ('date', models.DateField()),
                ('currency', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter_number', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_label', models.TextField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_of_measurement', models.TextField()),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.financialstatement')),
            ],
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.quarter'),
        ),
        migrations.CreateModel(
            name='FinancialRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_name', models.TextField()),
                ('ratio_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='AnalystEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst_name', models.TextField()),
                ('estimate_date', models.DateField()),
                ('estimate_type', models.TextField()),
                ('estimate_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.company')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.company')),
            ],
            options={
                'unique_together': {('company', 'date')},
            },
        ),
    ]
