# Generated by Django 3.2.23 on 2023-11-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ticker_symbol', models.TextField(unique=True)),
                ('cik', models.IntegerField(unique=True)),
                ('location', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='financial_statement_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_label', models.TextField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_of_measurement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='financial_statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('cash_flow', 'Cash Flow')])),
                ('date', models.DateField()),
                ('currency', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='quarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.companies')),
            ],
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='financialstatementitem',
            name='financial_statement',
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='company',
        ),
        migrations.RenameModel(
            old_name='AnalystEstimate',
            new_name='analyst_estimates',
        ),
        migrations.RenameModel(
            old_name='FinancialRatio',
            new_name='financial_ratios',
        ),
        migrations.RenameModel(
            old_name='MarketData',
            new_name='market_data',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='FinancialStatement',
        ),
        migrations.DeleteModel(
            name='FinancialStatementItem',
        ),
        migrations.DeleteModel(
            name='Quarter',
        ),
        migrations.AddField(
            model_name='financial_statements',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.quarters'),
        ),
        migrations.AddField(
            model_name='financial_statement_items',
            name='financial_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.financial_statements'),
        ),
        migrations.AlterField(
            model_name='analyst_estimates',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.companies'),
        ),
        migrations.AlterField(
            model_name='financial_ratios',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.quarters'),
        ),
        migrations.AlterField(
            model_name='market_data',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.companies'),
        ),
    ]
