# Generated by Django 3.2.23 on 2023-11-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_auto_20231126_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('label', models.TextField()),
                ('depth', models.IntegerField()),
                ('financial_statement_type', models.TextField()),
            ],
            options={
                'db_table': 'financial_statement_labels',
            },
        ),
    ]
