# Generated by Django 3.2.23 on 2023-11-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_financialstatementlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatementlabel',
            name='mapped_label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
