# Generated by Django 3.2.23 on 2023-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_watchedstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialstatementlabel',
            options={'ordering': ['ranking']},
        ),
        migrations.AddField(
            model_name='financialstatementlabel',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
