# Generated by Django 3.2.23 on 2023-11-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_auto_20231128_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='exchange',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='industry',
            field=models.TextField(null=True),
        ),
    ]
