# Generated by Django 3.2.23 on 2023-12-02 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0009_auto_20231129_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_data',
            name='dividend_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_value', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('market_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.market_data')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.portfolio')),
            ],
            options={
                'db_table': 'asset_holdings',
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='idx_portfolio_user'),
        ),
        migrations.AddIndex(
            model_name='assetholding',
            index=models.Index(fields=['portfolio'], name='idx_asset_holdings_portfolio'),
        ),
        migrations.AddIndex(
            model_name='assetholding',
            index=models.Index(fields=['market_data'], name='idx_asset_holdings_market_data'),
        ),
    ]
