# Generated by Django 3.2.23 on 2023-12-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_auto_20231202_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_data',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
