# Generated by Django 3.2.23 on 2023-12-04 20:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_comment_post_section_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_paragraph',
            field=models.TextField(default='Default text', help_text='Enter the first paragraph of the post'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(blank=True, help_text='URL of the image hosted on a third-party service', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
